name: daily-cron-pbook-test

on:
  schedule:
    - cron: '38 * * * *'


jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check the site everyday??
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://phonebook-part11.fly.dev

# Here's one for team Matti